### PR TITLE
Sanitize Implementation with Tests

### PR DESCRIPTION
**Pull request by nl356**
Created new MarkdownUtils.java in new folder to implement style text. 
No code yet.

### CODE REVIEW

**Comment by TylerSandman** [comment]
Note that when you commit to the same branch that corresponds to an existing pull request, the pull request itself gets updated with those commits. So in this case, this pull request is no longer "Created utils folder", but also sanitizing input and adding code. Is this your intention to have all this in one pull request? If not, you'll have to separate your pull requests into separate branches. If so, carry on : )

**Comment by trishazalani** [comment]
The code looks great and compilation is successful with all test cases passed! I have a few questions though. Are you handling incorrect messages with a string returned as "" (I understood this from your second test case). Also, have you called cleanmessage anywhere in the code yet? Moreover, since you are using the disallowing content method to sanitize your input, should I be still passing the HTML tags to you?

**Comment by nl356** [comment]
Yea, good questions!
Correct, anything detected to be malicious by JSoup's basic white list is filtered out (can adjust the list if need be). cleanmessage should be called by your parsing function, namely when it passes HTML tags to it (which you correctly stated).

**Comment by trishazalani** [comment]
So basically Ill use the html generated by the markdown and pass that string to your cleanmessage which will  handle the rest?

**Comment by nl356** [comment]
Ideally yes. May need to add some more tests (esp edge cases), but yes that was my reasoning! :)

**Comment by trishazalani** [comment]
Okay, LGTM!

**Pull request merged**
