### PR TITLE
Imported Library for Markdown

### PR DESCRIPTION
**Pull request by trishazalani**
I have imported the libraries required for the Markdown.

### CODE REVIEW

**Comment by nl356** [comment]
Just to make sure, you're utilizing open source material from: https://github.com/atlassian/commonmark-java ?
And this is for parsing and rendering to HTML?
Have you checked any effects of adding this dependency (there shouldn't be anything serious, but just in case)?

**Comment by trishazalani** [comment]
Yup, you are right. I haven't checked about any effects though. What do you mean by those?

**Comment by nl356** [comment]
Just that the original functionalities (prior to the addition of this code) still work.

**Comment by trishazalani** [comment]
All the test cases pass, so I think I'm not interfering with anything yet.

**Comment by nl356** [comment]
ok, LGTM

**Comment by trishazalani** [comment]
I have completed markdown, and added a test case to test its functionality as well. Markdown has been called in chatservlet, and the chatservlet test cases have been updated to allow bold html tags and other content from markdown. All functions in MarkDown utils have been changed to static to avoid instantiation. Let me know if there are any questions!

**Comment by nl356** [comment]
All test cases passing for me! 
Unfortunately after deploying to the app engine, there are now extra gaps in the messages. Not sure if it's a result of what we did or not... Though the bold, italicizing, and sanitizing is working perfectly fine! :) 
screenshot from 2018-04-27 16-05-27

**Comment by trishazalani** [comment]
Its probably because of the <p> and </p> tags generated due to markdown but I dont think there is much that I can do about that. Do you have any suggestions?

**Comment by trishazalani** [comment]
I meant "< p >" and "< \ p >" tags. (Cannot type them out as they result in the above).

**Comment by nl356** [comment]
hmm... i tried adjusting a couple things but nothing works... :( 
@TylerSandman any ideas?

**Comment by trishazalani** [comment]
I tried replacing the p tags with empty strings but that is giving weird results as well.

**Comment by TylerSandman** [comment]
This looks like this is happening due to how <p> tags are styled using CSS. Try adding something like the following to main.css:

#chat p {
  margin: 0
}

or #chat * p {
  margin: 0
}

**Comment by trishazalani** [comment]
Thanks Tyler! That worked!

**Pull request merged**
